"""AMG v2 CAD-native model namespace."""

from ai_mesh_generator.amg.model.part_classifier import (
    PART_CLASS_ORDER,
    PartClassifierError,
    PartClassifierTrainingResult,
    PartClassPrediction,
    extract_part_feature_matrix,
    load_part_classifier,
    predict_part_class,
    save_part_classifier,
    train_part_classifier,
)
from ai_mesh_generator.amg.model.quality_surrogate import (
    OptimizedSizeField,
    QualitySurrogateError,
    QualitySurrogateTrainingResult,
    build_quality_surrogate_training_matrix,
    load_quality_surrogate,
    optimize_size_field,
    predict_entity_quality,
    save_quality_surrogate,
    train_quality_surrogate,
    write_size_field,
)
from ai_mesh_generator.amg.model.segmentation import (
    EDGE_SEGMENTATION_CLASSES,
    FACE_SEGMENTATION_CLASSES,
    BrepSegmentationModel,
    EntityGraphTensors,
    SegmentationModelError,
    SegmentationOutput,
    SegmentationTargets,
    build_entity_graph_tensors,
    build_segmentation_targets,
)

__all__ = [
    "BrepSegmentationModel",
    "EDGE_SEGMENTATION_CLASSES",
    "EntityGraphTensors",
    "FACE_SEGMENTATION_CLASSES",
    "OptimizedSizeField",
    "PART_CLASS_ORDER",
    "PartClassPrediction",
    "PartClassifierError",
    "PartClassifierTrainingResult",
    "QualitySurrogateError",
    "QualitySurrogateTrainingResult",
    "SegmentationModelError",
    "SegmentationOutput",
    "SegmentationTargets",
    "build_entity_graph_tensors",
    "build_quality_surrogate_training_matrix",
    "build_segmentation_targets",
    "extract_part_feature_matrix",
    "load_part_classifier",
    "load_quality_surrogate",
    "optimize_size_field",
    "predict_entity_quality",
    "predict_part_class",
    "save_part_classifier",
    "save_quality_surrogate",
    "train_part_classifier",
    "train_quality_surrogate",
    "write_size_field",
]
