"""AMG v2 CAD-native model namespace."""

from ai_mesh_generator.amg.model.part_classifier import (
    PART_CLASS_ORDER,
    PartClassifierError,
    PartClassifierTrainingResult,
    PartClassPrediction,
    extract_part_feature_matrix,
    load_part_classifier,
    predict_part_class,
    save_part_classifier,
    train_part_classifier,
)
from ai_mesh_generator.amg.model.segmentation import (
    EDGE_SEGMENTATION_CLASSES,
    FACE_SEGMENTATION_CLASSES,
    BrepSegmentationModel,
    EntityGraphTensors,
    SegmentationModelError,
    SegmentationOutput,
    SegmentationTargets,
    build_entity_graph_tensors,
    build_segmentation_targets,
)
from ai_mesh_generator.amg.model.size_field import (
    BrepSizeFieldModel,
    SizeFieldGraphTensors,
    SizeFieldModelError,
    SizeFieldOutput,
    SizeFieldTargets,
    build_size_field_document,
    build_size_field_graph_tensors,
    build_size_field_targets,
    project_edge_sizes,
    project_face_sizes,
    write_size_field_document,
)

__all__ = [
    "BrepSegmentationModel",
    "BrepSizeFieldModel",
    "EDGE_SEGMENTATION_CLASSES",
    "EntityGraphTensors",
    "FACE_SEGMENTATION_CLASSES",
    "PART_CLASS_ORDER",
    "PartClassPrediction",
    "PartClassifierError",
    "PartClassifierTrainingResult",
    "SegmentationModelError",
    "SegmentationOutput",
    "SegmentationTargets",
    "SizeFieldGraphTensors",
    "SizeFieldModelError",
    "SizeFieldOutput",
    "SizeFieldTargets",
    "build_entity_graph_tensors",
    "build_segmentation_targets",
    "build_size_field_document",
    "build_size_field_graph_tensors",
    "build_size_field_targets",
    "extract_part_feature_matrix",
    "load_part_classifier",
    "project_edge_sizes",
    "project_face_sizes",
    "predict_part_class",
    "save_part_classifier",
    "train_part_classifier",
    "write_size_field_document",
]
